name: PR AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install requests

      - name: Extract PR Code
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         echo "Fetching PR code..."
           PR_FILES=$(gh pr diff --name-only ${{ github.event.pull_request.number }})
           echo "$PR_FILES" > changed_files.txt

      - name: Analyze Code with AI
        run: |
          echo "Reviewing code with AI..."
          python - <<EOF
          import requests
          import os

          API_URL = "https://api-inference.huggingface.co/models/facebook/bart-large-cnn"
          HEADERS = {"Authorization": f"Bearer {os.getenv('HUGGINGFACE_API_KEY')}"}

          with open("changed_files.txt", "r") as file:
              code_changes = file.read()

          payload = {"inputs": f"Analyze this code and suggest optimization:\n{code_changes}"}
          response = requests.post(API_URL, headers=HEADERS, json=payload)

          if response.status_code == 200:
              ai_suggestion = response.json()[0]["summary_text"]
          else:
              ai_suggestion = "AI analysis failed."

          print("AI Suggestion:", ai_suggestion)

          with open("comment.txt", "w") as f:
              f.write(f"**AI Code Review:**\n{ai_suggestion}")
          EOF

      - name: Post AI Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT=$(cat comment.txt)
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
