name: PR AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write  # 👈 Allows commenting on PRs

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Fetch changed files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching PR code..."
          PR_FILES=$(gh pr diff ${{ github.event.pull_request.number }} --name-only)
          echo "$PR_FILES" > changed_files.txt

      - name: Get AI Review from Free API
        run: |
          echo "Sending request to AI API..."

          API_RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
             -H "Content-Type: application/json" \
             -d '{
             "contents": [{
                 "parts": [{"text": "'"$(cat changed_files.txt)"'"}]
             }]
          }')

          echo "AI API Response: $API_RESPONSE"

          if [[ -z "$API_RESPONSE" || "$API_RESPONSE" == "null" ]]; then
              echo "AI analysis failed." > comment.txt
          else
              echo "AI Code Review: $API_RESPONSE" > comment.txt
          fi

      - name: Post AI Review as PR Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT=$(cat comment.txt)
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"

